"""empty message

Revision ID: 06b743a56955
Revises: 37c304476a5a
Create Date: 2024-04-14 11:03:07.556451

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06b743a56955'
down_revision = '37c304476a5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payroll_tbl', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_tardiness', sa.Float(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payroll_tbl', schema=None) as batch_op:
        batch_op.drop_column('total_tardiness')

    # ### end Alembic commands ###
