"""empty message

Revision ID: 0892dc3716a7
Revises: 503d4d5f9f2d
Create Date: 2024-04-11 23:05:56.995275

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0892dc3716a7'
down_revision = '503d4d5f9f2d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory_tbl', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unit_price', sa.Float(), nullable=True))

    with op.batch_alter_table('purchase_order_tbl', schema=None) as batch_op:
        batch_op.drop_column('item_name')
        batch_op.drop_column('category')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchase_order_tbl', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('item_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))

    with op.batch_alter_table('inventory_tbl', schema=None) as batch_op:
        batch_op.drop_column('unit_price')

    # ### end Alembic commands ###
