"""empty message

Revision ID: 0d0f4961764b
Revises: 5f86e5bf2203
Create Date: 2024-04-15 13:12:23.917509

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d0f4961764b'
down_revision = '5f86e5bf2203'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee_request_order_tbl', schema=None) as batch_op:
        batch_op.add_column(sa.Column('approved_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('received_by', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('received_date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee_request_order_tbl', schema=None) as batch_op:
        batch_op.drop_column('received_date')
        batch_op.drop_column('received_by')
        batch_op.drop_column('approved_date')

    # ### end Alembic commands ###
