"""empty message

Revision ID: 0f76790702df
Revises: 0a8d1af627a3
Create Date: 2024-04-09 12:00:14.178732

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0f76790702df'
down_revision = '0a8d1af627a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_addon_tbl',
    sa.Column('service_addon_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('service_addon_id')
    )
    with op.batch_alter_table('booking_tbl', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time_arrival', sa.DateTime(), nullable=False))
        batch_op.drop_column('time_slot')

    with op.batch_alter_table('service_tbl', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_price', sa.Float(), nullable=False))
        batch_op.drop_column('duration')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_tbl', schema=None) as batch_op:
        batch_op.add_column(sa.Column('duration', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
        batch_op.drop_column('total_price')

    with op.batch_alter_table('booking_tbl', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time_slot', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
        batch_op.drop_column('time_arrival')

    op.drop_table('service_addon_tbl')
    # ### end Alembic commands ###
