"""empty message

Revision ID: 10ec45a091f1
Revises: 3e785f25406d
Create Date: 2024-04-29 12:20:30.842620

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10ec45a091f1'
down_revision = '3e785f25406d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('booking_employee_association',
    sa.Column('booking_id', sa.Integer(), nullable=True),
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['booking_tbl.booking_id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employee_tbl.employee_id'], )
    )
    with op.batch_alter_table('booking_tbl', schema=None) as batch_op:
        batch_op.drop_constraint('booking_tbl_employee_id_fkey', type_='foreignkey')
        batch_op.drop_column('employee_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking_tbl', schema=None) as batch_op:
        batch_op.add_column(sa.Column('employee_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('booking_tbl_employee_id_fkey', 'employee_tbl', ['employee_id'], ['employee_id'])

    op.drop_table('booking_employee_association')
    # ### end Alembic commands ###
