"""empty message

Revision ID: 126a59c90cd5
Revises: f2e064b39657
Create Date: 2024-04-10 02:19:42.068439

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '126a59c90cd5'
down_revision = 'f2e064b39657'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking_tbl', schema=None) as batch_op:
        batch_op.add_column(sa.Column('property_size', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('additional_charge', sa.Float(), nullable=False))
        batch_op.alter_column('total_price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)

    with op.batch_alter_table('service_addon_tbl', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pricing_description', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_addon_tbl', schema=None) as batch_op:
        batch_op.drop_column('pricing_description')

    with op.batch_alter_table('booking_tbl', schema=None) as batch_op:
        batch_op.alter_column('total_price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
        batch_op.drop_column('additional_charge')
        batch_op.drop_column('property_size')

    # ### end Alembic commands ###
