"""empty message

Revision ID: 14d024c86d8e
Revises: 126a59c90cd5
Create Date: 2024-04-10 14:19:05.810344

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14d024c86d8e'
down_revision = '126a59c90cd5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('billing_tbl', schema=None) as batch_op:
        batch_op.add_column(sa.Column('service_status', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('billing_tbl', schema=None) as batch_op:
        batch_op.drop_column('service_status')

    # ### end Alembic commands ###
