"""reconfig booking_tbl

Revision ID: 1da0aa55788a
Revises: 5298ecfdf1f7
Create Date: 2024-04-09 17:07:46.926863

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1da0aa55788a'
down_revision = '5298ecfdf1f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('booking_service_addon_association',
    sa.Column('booking_id', sa.Integer(), nullable=True),
    sa.Column('service_addon_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['booking_tbl.booking_id'], ),
    sa.ForeignKeyConstraint(['service_addon_id'], ['service_addon_tbl.service_addon_id'], )
    )
    with op.batch_alter_table('booking_tbl', schema=None) as batch_op:
        batch_op.drop_constraint('booking_tbl_service_addon_id_fkey', type_='foreignkey')
        batch_op.drop_column('service_addon_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking_tbl', schema=None) as batch_op:
        batch_op.add_column(sa.Column('service_addon_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('booking_tbl_service_addon_id_fkey', 'service_addon_tbl', ['service_addon_id'], ['service_addon_id'])

    op.drop_table('booking_service_addon_association')
    # ### end Alembic commands ###
