"""empty message

Revision ID: 25e284b0d544
Revises: 50cf738a2645
Create Date: 2024-05-03 20:39:13.165805

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25e284b0d544'
down_revision = '50cf738a2645'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee_tbl', schema=None) as batch_op:
        batch_op.add_column(sa.Column('consecutive_failed_login', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('failed_timer', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee_tbl', schema=None) as batch_op:
        batch_op.drop_column('failed_timer')
        batch_op.drop_column('consecutive_failed_login')

    # ### end Alembic commands ###
