"""empty message

Revision ID: 25f8fc5a779f
Revises: 
Create Date: 2024-03-25 00:51:43.101618

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25f8fc5a779f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer_address', schema=None) as batch_op:
        batch_op.alter_column('houseno', new_column_name='houseno_street')


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer_address', schema=None) as batch_op:
        batch_op.alter_column('houseno_street', new_column_name='houseno')



