"""empty message

Revision ID: 2a0f9ace3443
Revises: aba7ef779767
Create Date: 2024-04-21 20:44:01.992904

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a0f9ace3443'
down_revision = 'aba7ef779767'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payroll_contribution_rate_tbl', schema=None) as batch_op:
        batch_op.alter_column('minimum_rate',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payroll_contribution_rate_tbl', schema=None) as batch_op:
        batch_op.alter_column('minimum_rate',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)

    # ### end Alembic commands ###
