"""empty message

Revision ID: 2f7862acdd62
Revises: 2a0f9ace3443
Create Date: 2024-04-21 21:14:48.309987

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f7862acdd62'
down_revision = '2a0f9ace3443'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payroll_contribution_rate_tbl')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payroll_contribution_rate_tbl',
    sa.Column('sss', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('philhealth', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('pagibig', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('payroll_contribution_rate_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('minimum_rate', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('year', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.UniqueConstraint('year', name='payroll_contribution_rate_tbl_year_key')
    )
    # ### end Alembic commands ###
