"""empty message

Revision ID: 30bdc4081014
Revises: 81f27ffc2486
Create Date: 2024-04-29 17:09:56.993148

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30bdc4081014'
down_revision = '81f27ffc2486'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking_tbl', schema=None) as batch_op:
        batch_op.add_column(sa.Column('booking_status', sa.String(length=250), nullable=False))
        batch_op.drop_column('status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking_tbl', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.VARCHAR(length=250), autoincrement=False, nullable=False))
        batch_op.drop_column('booking_status')

    # ### end Alembic commands ###
