"""empty message

Revision ID: 328bbddaa8cb
Revises: e2913ced2510
Create Date: 2024-05-03 13:36:51.133817

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '328bbddaa8cb'
down_revision = 'e2913ced2510'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer_tbl', schema=None) as batch_op:
        batch_op.alter_column('last_name',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
        batch_op.drop_column('google_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer_tbl', schema=None) as batch_op:
        batch_op.add_column(sa.Column('google_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.alter_column('last_name',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)

    # ### end Alembic commands ###
