"""empty message

Revision ID: 37c304476a5a
Revises: b999fd58ae47
Create Date: 2024-04-14 10:34:31.830940

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37c304476a5a'
down_revision = 'b999fd58ae47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payroll_tbl', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_payroll_record', ['employee_id', 'period_start', 'period_end'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payroll_tbl', schema=None) as batch_op:
        batch_op.drop_constraint('unique_payroll_record', type_='unique')

    # ### end Alembic commands ###
