"""empty message

Revision ID: 3b6912548206
Revises: b6b10821dbae
Create Date: 2024-04-29 06:33:02.511504

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3b6912548206'
down_revision = 'b6b10821dbae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('superadmin_login_tbl', schema=None) as batch_op:
        batch_op.alter_column('failed_timer',
               existing_type=postgresql.TIME(),
               type_=sa.DateTime(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('superadmin_login_tbl', schema=None) as batch_op:
        batch_op.alter_column('failed_timer',
               existing_type=sa.DateTime(),
               type_=postgresql.TIME(),
               existing_nullable=True)

    # ### end Alembic commands ###
