"""empty message

Revision ID: 3be4edb2c65a
Revises: 6386e9663def
Create Date: 2024-04-12 12:41:39.922876

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3be4edb2c65a'
down_revision = '6386e9663def'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchase_order_inventory_association', schema=None) as batch_op:
        batch_op.add_column(sa.Column('item_qty', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchase_order_inventory_association', schema=None) as batch_op:
        batch_op.drop_column('item_qty')

    # ### end Alembic commands ###
