"""empty message

Revision ID: 3e785f25406d
Revises: 3b6912548206
Create Date: 2024-04-29 07:16:08.519354

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e785f25406d'
down_revision = '3b6912548206'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking_tbl', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notes', sa.String(length=250), nullable=True))

    with op.batch_alter_table('superadmin_login_tbl', schema=None) as batch_op:
        batch_op.add_column(sa.Column('consecutive_failed_login', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('failed_timer', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('superadmin_login_tbl', schema=None) as batch_op:
        batch_op.drop_column('failed_timer')
        batch_op.drop_column('consecutive_failed_login')

    with op.batch_alter_table('booking_tbl', schema=None) as batch_op:
        batch_op.drop_column('notes')

    # ### end Alembic commands ###
