"""empty message

Revision ID: 4b06c0525c5e
Revises: 6bbefa2b2ba6
Create Date: 2024-05-03 14:36:43.408833

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b06c0525c5e'
down_revision = '6bbefa2b2ba6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer_tbl', schema=None) as batch_op:
        batch_op.add_column(sa.Column('google_id', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer_tbl', schema=None) as batch_op:
        batch_op.drop_column('google_id')

    # ### end Alembic commands ###
