"""empty message

Revision ID: 4b7b4e2749d0
Revises: 06b743a56955
Create Date: 2024-04-14 11:55:28.894154

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b7b4e2749d0'
down_revision = '06b743a56955'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payroll_contribution_rate_tbl',
    sa.Column('payroll_contribution_id', sa.Integer(), nullable=False),
    sa.Column('sss', sa.Float(), nullable=False),
    sa.Column('philhealth', sa.Float(), nullable=False),
    sa.Column('pagibig', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('payroll_contribution_id')
    )
    op.drop_table('payroll_contribution_tbl')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payroll_contribution_tbl',
    sa.Column('payroll_contribution_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('sss', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('philhealth', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('pagibig', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('payroll_contribution_id', name='payroll_contribution_tbl_pkey')
    )
    op.drop_table('payroll_contribution_rate_tbl')
    # ### end Alembic commands ###
