"""empty message

Revision ID: 4fea898a4955
Revises: db5ad646fa48
Create Date: 2024-04-15 05:22:11.407536

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4fea898a4955'
down_revision = 'db5ad646fa48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee_request_order_tbl', schema=None) as batch_op:
        batch_op.alter_column('approved_by',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee_request_order_tbl', schema=None) as batch_op:
        batch_op.alter_column('approved_by',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)

    # ### end Alembic commands ###
