"""empty message

Revision ID: 503d4d5f9f2d
Revises: 14d024c86d8e
Create Date: 2024-04-10 18:02:47.474352

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '503d4d5f9f2d'
down_revision = '14d024c86d8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer_feedback_tbl', schema=None) as batch_op:
        batch_op.drop_constraint('customer_feedback_tbl_service_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('customer_feedback_tbl_customer_id_fkey', type_='foreignkey')
        batch_op.drop_column('service_id')
        batch_op.drop_column('customer_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer_feedback_tbl', schema=None) as batch_op:
        batch_op.add_column(sa.Column('customer_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('service_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('customer_feedback_tbl_customer_id_fkey', 'customer_tbl', ['customer_id'], ['customer_id'])
        batch_op.create_foreign_key('customer_feedback_tbl_service_id_fkey', 'service_tbl', ['service_id'], ['service_id'])

    # ### end Alembic commands ###
