"""empty message

Revision ID: 50cf738a2645
Revises: 4b06c0525c5e
Create Date: 2024-05-03 20:18:58.639662

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50cf738a2645'
down_revision = '4b06c0525c5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee_attendance_activity_logs_tbl', schema=None) as batch_op:
        batch_op.add_column(sa.Column('log_location', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee_attendance_activity_logs_tbl', schema=None) as batch_op:
        batch_op.drop_column('log_location')

    # ### end Alembic commands ###
