"""empty message

Revision ID: 56f3a199f5f9
Revises: ec2a7fee9445
Create Date: 2024-04-27 21:04:10.287818

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56f3a199f5f9'
down_revision = 'ec2a7fee9445'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('booking_admin_activity_logs_tbl',
    sa.Column('log_id', sa.Integer(), nullable=False),
    sa.Column('login_id', sa.Integer(), nullable=True),
    sa.Column('logs_description', sa.String(length=255), nullable=False),
    sa.Column('log_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['login_id'], ['billing_admin_login_tbl.login_id'], ),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_table('customer_admin_activity_logs_tbl',
    sa.Column('log_id', sa.Integer(), nullable=False),
    sa.Column('login_id', sa.Integer(), nullable=True),
    sa.Column('logs_description', sa.String(length=255), nullable=False),
    sa.Column('log_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['login_id'], ['customer_admin_login_tbl.login_id'], ),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_table('employee_admin_activity_logs_tbl',
    sa.Column('log_id', sa.Integer(), nullable=False),
    sa.Column('login_id', sa.Integer(), nullable=True),
    sa.Column('logs_description', sa.String(length=255), nullable=False),
    sa.Column('log_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['login_id'], ['employee_admin_login_tbl.login_id'], ),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_table('inventory_admin_activity_logs_tbl',
    sa.Column('log_id', sa.Integer(), nullable=False),
    sa.Column('login_id', sa.Integer(), nullable=True),
    sa.Column('logs_description', sa.String(length=255), nullable=False),
    sa.Column('log_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['login_id'], ['inventory_admin_login_tbl.login_id'], ),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_table('superadmin_activity_logs_tbl',
    sa.Column('log_id', sa.Integer(), nullable=False),
    sa.Column('login_id', sa.Integer(), nullable=True),
    sa.Column('logs_description', sa.String(length=255), nullable=False),
    sa.Column('log_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['login_id'], ['superadmin_login_tbl.login_id'], ),
    sa.PrimaryKeyConstraint('log_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('superadmin_activity_logs_tbl')
    op.drop_table('inventory_admin_activity_logs_tbl')
    op.drop_table('employee_admin_activity_logs_tbl')
    op.drop_table('customer_admin_activity_logs_tbl')
    op.drop_table('booking_admin_activity_logs_tbl')
    # ### end Alembic commands ###
