"""empty message

Revision ID: 58ea1a786e40
Revises: 4b7b4e2749d0
Create Date: 2024-04-14 11:56:19.572913

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58ea1a786e40'
down_revision = '4b7b4e2749d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payroll_contribution_rate_tbl', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payroll_contribution_rate_id', sa.Integer(), nullable=False))
        batch_op.drop_column('payroll_contribution_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payroll_contribution_rate_tbl', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payroll_contribution_id', sa.INTEGER(), autoincrement=True, nullable=False))
        batch_op.drop_column('payroll_contribution_rate_id')

    # ### end Alembic commands ###
