"""empty message

Revision ID: 5a40a0743998
Revises: ed87a58e81d0
Create Date: 2024-04-23 17:56:54.115154

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a40a0743998'
down_revision = 'ed87a58e81d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('property_size_pricing_tbl', schema=None) as batch_op:
        batch_op.drop_column('add_price_per_floor')

    with op.batch_alter_table('service_tbl', schema=None) as batch_op:
        batch_op.add_column(sa.Column('add_price_per_floor', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_tbl', schema=None) as batch_op:
        batch_op.drop_column('add_price_per_floor')

    with op.batch_alter_table('property_size_pricing_tbl', schema=None) as batch_op:
        batch_op.add_column(sa.Column('add_price_per_floor', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
