"""empty message

Revision ID: 6386e9663def
Revises: 0892dc3716a7
Create Date: 2024-04-12 09:31:07.211612

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6386e9663def'
down_revision = '0892dc3716a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('purchase_order_inventory_association',
    sa.Column('purchase_order_id', sa.Integer(), nullable=True),
    sa.Column('inventory_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['inventory_id'], ['inventory_tbl.inventory_id'], ),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_order_tbl.purchase_order_id'], )
    )
    with op.batch_alter_table('purchase_order_tbl', schema=None) as batch_op:
        batch_op.drop_constraint('purchase_order_tbl_inventory_id_fkey', type_='foreignkey')
        batch_op.drop_column('inventory_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchase_order_tbl', schema=None) as batch_op:
        batch_op.add_column(sa.Column('inventory_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('purchase_order_tbl_inventory_id_fkey', 'inventory_tbl', ['inventory_id'], ['inventory_id'])

    op.drop_table('purchase_order_inventory_association')
    # ### end Alembic commands ###
