"""empty message

Revision ID: 6c908466b6e5
Revises: a39c1b7b8ab0
Create Date: 2024-05-03 09:59:59.862403

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c908466b6e5'
down_revision = 'a39c1b7b8ab0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer_tbl', schema=None) as batch_op:
        batch_op.drop_column('registration_type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer_tbl', schema=None) as batch_op:
        batch_op.add_column(sa.Column('registration_type', sa.VARCHAR(length=100), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
