"""empty message

Revision ID: 8013dd773e26
Revises: 
Create Date: 2024-04-06 00:41:06.947280

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8013dd773e26'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('billing_admin_login_tbl',
    sa.Column('login_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('email_confirm', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('login_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('customer_admin_login_tbl',
    sa.Column('login_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('email_confirm', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('login_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('customer_tbl',
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=250), nullable=False),
    sa.Column('middle_name', sa.String(length=250), nullable=True),
    sa.Column('last_name', sa.String(length=250), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.Column('phone', sa.String(length=11), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('email_confirm', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('customer_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('employee_admin_login_tbl',
    sa.Column('login_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('email_confirm', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('login_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('employee_tbl',
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=250), nullable=False),
    sa.Column('middle_name', sa.String(length=250), nullable=True),
    sa.Column('last_name', sa.String(length=250), nullable=False),
    sa.Column('address', sa.String(length=250), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.Column('phone', sa.String(length=11), nullable=False),
    sa.Column('position', sa.String(length=100), nullable=False),
    sa.Column('hire_date', sa.Date(), nullable=True),
    sa.Column('daily_rate', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('email_confirm', sa.Boolean(), nullable=True),
    sa.Column('de_minimis', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('employee_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('inventory_admin_login_tbl',
    sa.Column('login_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('email_confirm', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('login_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('payroll_admin_login_tbl',
    sa.Column('login_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('email_confirm', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('login_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('payroll_contribution_tbl',
    sa.Column('payroll_contribution_id', sa.Integer(), nullable=False),
    sa.Column('sss_contribution', sa.Float(), nullable=False),
    sa.Column('philhealth_contribution', sa.Float(), nullable=False),
    sa.Column('pagibig_contribution', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('payroll_contribution_id')
    )
    op.create_table('service_tbl',
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=255), nullable=False),
    sa.Column('duration', sa.Float(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('service_id')
    )
    op.create_table('superadmin_login_tbl',
    sa.Column('login_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('email_confirm', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('login_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('supplier_tbl',
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('supplier_name', sa.String(length=255), nullable=False),
    sa.Column('contact_person', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('supplier_id')
    )
    op.create_table('attendance_tbl',
    sa.Column('attendance_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.Column('work_date', sa.Date(), nullable=False),
    sa.Column('login_time', sa.DateTime(), nullable=True),
    sa.Column('logout_time', sa.DateTime(), nullable=True),
    sa.Column('login_status', sa.String(length=50), nullable=True),
    sa.Column('logout_status', sa.String(length=50), nullable=True),
    sa.Column('tardiness', sa.Integer(), nullable=True),
    sa.Column('ot_hrs', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employee_tbl.employee_id'], ),
    sa.PrimaryKeyConstraint('attendance_id'),
    sa.UniqueConstraint('employee_id', 'work_date', name='_employee_work_date_uc')
    )
    op.create_table('booking_tbl',
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('service_id', sa.Integer(), nullable=True),
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.Column('booking_date', sa.Date(), nullable=False),
    sa.Column('time_slot', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=250), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customer_tbl.customer_id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employee_tbl.employee_id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['service_tbl.service_id'], ),
    sa.PrimaryKeyConstraint('booking_id')
    )
    op.create_table('customer_address',
    sa.Column('address_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('houseno_street', sa.String(length=100), nullable=False),
    sa.Column('barangay', sa.String(length=100), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('region', sa.String(length=100), nullable=False),
    sa.Column('zipcode', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customer_tbl.customer_id'], ),
    sa.PrimaryKeyConstraint('address_id')
    )
    op.create_table('inventory_tbl',
    sa.Column('inventory_id', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(length=255), nullable=False),
    sa.Column('item_name', sa.String(length=255), nullable=False),
    sa.Column('available_stock', sa.Integer(), nullable=False),
    sa.Column('used_item', sa.Integer(), nullable=False),
    sa.Column('reorder_level', sa.Integer(), nullable=True),
    sa.Column('item_status', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['supplier_id'], ['supplier_tbl.supplier_id'], ),
    sa.PrimaryKeyConstraint('inventory_id')
    )
    op.create_table('payroll_tbl',
    sa.Column('payroll_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('total_ot_hrs', sa.Float(), nullable=False),
    sa.Column('base_salary', sa.Float(), nullable=False),
    sa.Column('gross_pay', sa.Float(), nullable=False),
    sa.Column('net_pay', sa.Float(), nullable=False),
    sa.Column('thirteenth_month_pay', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employee_tbl.employee_id'], ),
    sa.PrimaryKeyConstraint('payroll_id')
    )
    op.create_table('schedule_tbl',
    sa.Column('schedule_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('end_time', sa.Time(), nullable=True),
    sa.Column('day_off', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employee_tbl.employee_id'], ),
    sa.PrimaryKeyConstraint('schedule_id')
    )
    op.create_table('billing_tbl',
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('payment_status', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['booking_tbl.booking_id'], ),
    sa.PrimaryKeyConstraint('invoice_id'),
    sa.UniqueConstraint('booking_id')
    )
    op.create_table('employee_request_order_tbl',
    sa.Column('employee_order_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('inventory_id', sa.Integer(), nullable=True),
    sa.Column('total_item_qty', sa.Integer(), nullable=False),
    sa.Column('order_date', sa.Date(), nullable=False),
    sa.Column('approved_by', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employee_tbl.employee_id'], ),
    sa.ForeignKeyConstraint(['inventory_id'], ['inventory_tbl.inventory_id'], ),
    sa.PrimaryKeyConstraint('employee_order_id')
    )
    op.create_table('payroll_deduction_tbl',
    sa.Column('payroll_deduction_id', sa.Integer(), nullable=False),
    sa.Column('payroll_id', sa.Integer(), nullable=True),
    sa.Column('sss_contribution', sa.Float(), nullable=False),
    sa.Column('philhealth_contribution', sa.Float(), nullable=False),
    sa.Column('pagibig_contribution', sa.Float(), nullable=False),
    sa.Column('withholding_tax', sa.Float(), nullable=False),
    sa.Column('other_deductions', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['payroll_id'], ['payroll_tbl.payroll_id'], ),
    sa.PrimaryKeyConstraint('payroll_deduction_id')
    )
    op.create_table('purchase_order_tbl',
    sa.Column('purchase_order_id', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=True),
    sa.Column('inventory_id', sa.Integer(), nullable=True),
    sa.Column('total_item_qty', sa.Integer(), nullable=False),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('prepared_by', sa.String(length=255), nullable=False),
    sa.Column('prepared_date', sa.Date(), nullable=False),
    sa.Column('received_by', sa.String(length=255), nullable=True),
    sa.Column('received_date', sa.DateTime(), nullable=True),
    sa.Column('category', sa.String(length=255), nullable=True),
    sa.Column('item_name', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['inventory_id'], ['inventory_tbl.inventory_id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['supplier_tbl.supplier_id'], ),
    sa.PrimaryKeyConstraint('purchase_order_id')
    )
    op.create_table('customer_feedback_tbl',
    sa.Column('customer_feedback_id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('comment', sa.String(length=255), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('rating_status', sa.String(length=20), nullable=True),
    sa.CheckConstraint('rating >= 1 AND rating <= 5', name='valid_rating'),
    sa.ForeignKeyConstraint(['customer_id'], ['customer_tbl.customer_id'], ),
    sa.ForeignKeyConstraint(['invoice_id'], ['billing_tbl.invoice_id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['service_tbl.service_id'], ),
    sa.PrimaryKeyConstraint('customer_feedback_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('customer_feedback_tbl')
    op.drop_table('purchase_order_tbl')
    op.drop_table('payroll_deduction_tbl')
    op.drop_table('employee_request_order_tbl')
    op.drop_table('billing_tbl')
    op.drop_table('schedule_tbl')
    op.drop_table('payroll_tbl')
    op.drop_table('inventory_tbl')
    op.drop_table('customer_address')
    op.drop_table('booking_tbl')
    op.drop_table('attendance_tbl')
    op.drop_table('supplier_tbl')
    op.drop_table('superadmin_login_tbl')
    op.drop_table('service_tbl')
    op.drop_table('payroll_contribution_tbl')
    op.drop_table('payroll_admin_login_tbl')
    op.drop_table('inventory_admin_login_tbl')
    op.drop_table('employee_tbl')
    op.drop_table('employee_admin_login_tbl')
    op.drop_table('customer_tbl')
    op.drop_table('customer_admin_login_tbl')
    op.drop_table('billing_admin_login_tbl')
    # ### end Alembic commands ###
