"""empty message

Revision ID: 924adbb32b35
Revises: 2f7862acdd62
Create Date: 2024-04-21 21:21:18.853457

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '924adbb32b35'
down_revision = '2f7862acdd62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payroll_contribution_tbl',
    sa.Column('payroll_contribution_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('sss', sa.Float(), nullable=False),
    sa.Column('philhealth', sa.Float(), nullable=False),
    sa.Column('pagibig', sa.Float(), nullable=False),
    sa.Column('minimum_rate', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('payroll_contribution_id'),
    sa.UniqueConstraint('year')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payroll_contribution_tbl')
    # ### end Alembic commands ###
