"""empty message

Revision ID: 9529f1810128
Revises: 25e284b0d544
Create Date: 2024-05-05 14:25:38.540140

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9529f1810128'
down_revision = '25e284b0d544'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('property_size_pricing_tbl', schema=None) as batch_op:
        batch_op.add_column(sa.Column('add_price_per_floor', sa.Float(), nullable=True))

    with op.batch_alter_table('service_tbl', schema=None) as batch_op:
        batch_op.drop_column('add_price_per_floor')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_tbl', schema=None) as batch_op:
        batch_op.add_column(sa.Column('add_price_per_floor', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))

    with op.batch_alter_table('property_size_pricing_tbl', schema=None) as batch_op:
        batch_op.drop_column('add_price_per_floor')

    # ### end Alembic commands ###
