"""empty message

Revision ID: a39c1b7b8ab0
Revises: eb9d0d55f620
Create Date: 2024-05-03 02:20:34.690749

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a39c1b7b8ab0'
down_revision = 'eb9d0d55f620'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer_tbl', schema=None) as batch_op:
        batch_op.add_column(sa.Column('registration_type', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer_tbl', schema=None) as batch_op:
        batch_op.drop_column('registration_type')

    # ### end Alembic commands ###
