"""empty message

Revision ID: aba7ef779767
Revises: 0511f5deeecc
Create Date: 2024-04-20 14:45:04.201349

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aba7ef779767'
down_revision = '0511f5deeecc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payroll_contribution_rate_tbl', schema=None) as batch_op:
        batch_op.add_column(sa.Column('year', sa.Integer(), nullable=False))
        batch_op.create_unique_constraint(None, ['year'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payroll_contribution_rate_tbl', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('year')

    # ### end Alembic commands ###
