"""empty message

Revision ID: b6b10821dbae
Revises: 34ccda31b869
Create Date: 2024-04-28 22:49:54.937192

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import text


# revision identifiers, used by Alembic.
revision = 'b6b10821dbae'
down_revision = '34ccda31b869'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('superadmin_login_tbl', schema=None) as batch_op:
        batch_op.drop_column('failed_timer')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('superadmin_login_tbl', schema=None) as batch_op:
        batch_op.drop_column('failed_timer')
        batch_op.drop_column('consecutive_failed_login')

    # ### end Alembic commands ###
