"""empty message

Revision ID: b85c7edc8df3
Revises: d9153e339490
Create Date: 2024-04-10 00:50:39.545608

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b85c7edc8df3'
down_revision = 'd9153e339490'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('billing_tbl', schema=None) as batch_op:
        batch_op.alter_column('method_of_payment',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)

    with op.batch_alter_table('booking_tbl', schema=None) as batch_op:
        batch_op.add_column(sa.Column('customer_address', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'customer_address', ['customer_address'], ['address_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking_tbl', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('customer_address')

    with op.batch_alter_table('billing_tbl', schema=None) as batch_op:
        batch_op.alter_column('method_of_payment',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)

    # ### end Alembic commands ###
