"""empty message

Revision ID: b999fd58ae47
Revises: f6212f495230
Create Date: 2024-04-14 10:21:14.031240

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b999fd58ae47'
down_revision = 'f6212f495230'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payroll_contribution_tbl', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sss', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('philhealth', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('pagibig', sa.Float(), nullable=False))
        batch_op.drop_column('philhealth_contribution')
        batch_op.drop_column('sss_contribution')
        batch_op.drop_column('pagibig_contribution')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payroll_contribution_tbl', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pagibig_contribution', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('sss_contribution', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('philhealth_contribution', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
        batch_op.drop_column('pagibig')
        batch_op.drop_column('philhealth')
        batch_op.drop_column('sss')

    # ### end Alembic commands ###
