"""empty message

Revision ID: c13bf6ea22e2
Revises: 3be4edb2c65a
Create Date: 2024-04-12 20:19:19.755553

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c13bf6ea22e2'
down_revision = '3be4edb2c65a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchase_order_inventory_association', schema=None) as batch_op:
        batch_op.alter_column('item_qty',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchase_order_inventory_association', schema=None) as batch_op:
        batch_op.alter_column('item_qty',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
