"""add payment_method in billing_tbl

Revision ID: d7eb3e89fb93
Revises: e07811a786e2
Create Date: 2024-04-09 21:55:44.175307

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7eb3e89fb93'
down_revision = 'e07811a786e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('billing_tbl', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_method', sa.String(length=100), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('billing_tbl', schema=None) as batch_op:
        batch_op.drop_column('payment_method')

    # ### end Alembic commands ###
