"""empty message

Revision ID: d88682868c75
Revises: 
Create Date: 2024-03-06 23:29:46.518807

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd88682868c75'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory_tbl', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=255), nullable=False))
        batch_op.drop_column('item_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory_tbl', schema=None) as batch_op:
        batch_op.add_column(sa.Column('item_name', sa.VARCHAR(length=255), nullable=False))
        batch_op.drop_column('description')

    # ### end Alembic commands ###
