"""add relationship between customer_tbl and billing_tbl

Revision ID: d9153e339490
Revises: 9371a2a1a496
Create Date: 2024-04-09 23:29:27.642056

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9153e339490'
down_revision = '9371a2a1a496'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('billing_tbl', schema=None) as batch_op:
        batch_op.add_column(sa.Column('method_of_payment', sa.String(length=100), nullable=True))
        batch_op.drop_column('payment_method')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('billing_tbl', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_method', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.drop_column('method_of_payment')

    # ### end Alembic commands ###
