"""empty message

Revision ID: db5ad646fa48
Revises: 16db7e022b0e
Create Date: 2024-04-14 19:55:56.381583

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db5ad646fa48'
down_revision = '16db7e022b0e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payroll_tbl', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_days_of_work', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payroll_tbl', schema=None) as batch_op:
        batch_op.drop_column('total_days_of_work')

    # ### end Alembic commands ###
