"""empty message

Revision ID: ea6992c14e9c
Revises: 5d3cb21d8c8b
Create Date: 2024-04-13 00:38:14.763767

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea6992c14e9c'
down_revision = '5d3cb21d8c8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchase_order_inventory_association', schema=None) as batch_op:
        batch_op.drop_column('item_qty')
        batch_op.drop_column('inventory_association_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchase_order_inventory_association', schema=None) as batch_op:
        batch_op.add_column(sa.Column('inventory_association_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('item_qty', sa.INTEGER(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
