"""empty message

Revision ID: eb9d0d55f620
Revises: c4c79320f741
Create Date: 2024-05-02 16:38:23.257468

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb9d0d55f620'
down_revision = 'c4c79320f741'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employee_attendance_activity_logs_tbl',
    sa.Column('log_id', sa.Integer(), nullable=False),
    sa.Column('login_id', sa.Integer(), nullable=True),
    sa.Column('logs_description', sa.String(length=255), nullable=False),
    sa.Column('log_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['login_id'], ['employee_tbl.employee_id'], ),
    sa.PrimaryKeyConstraint('log_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('employee_attendance_activity_logs_tbl')
    # ### end Alembic commands ###
