"""empty message

Revision ID: ec2a7fee9445
Revises: 5a40a0743998
Create Date: 2024-04-27 09:33:06.804258

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec2a7fee9445'
down_revision = '5a40a0743998'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance_tbl', schema=None) as batch_op:
        batch_op.add_column(sa.Column('login_location', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('logout_location', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance_tbl', schema=None) as batch_op:
        batch_op.drop_column('logout_location')
        batch_op.drop_column('login_location')

    # ### end Alembic commands ###
