"""empty message

Revision ID: ed87a58e81d0
Revises: edc2000ce493
Create Date: 2024-04-23 17:53:34.998801

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed87a58e81d0'
down_revision = 'edc2000ce493'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('property_size_pricing_tbl', schema=None) as batch_op:
        batch_op.add_column(sa.Column('add_price_per_floor', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('property_size_pricing_tbl', schema=None) as batch_op:
        batch_op.drop_column('add_price_per_floor')

    # ### end Alembic commands ###
