"""empty message

Revision ID: f2e064b39657
Revises: b85c7edc8df3
Create Date: 2024-04-10 00:57:59.626276

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2e064b39657'
down_revision = 'b85c7edc8df3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking_tbl', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('booking_tbl_customer_address_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'customer_address', ['address_id'], ['address_id'])
        batch_op.drop_column('customer_address')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking_tbl', schema=None) as batch_op:
        batch_op.add_column(sa.Column('customer_address', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('booking_tbl_customer_address_fkey', 'customer_address', ['customer_address'], ['address_id'])
        batch_op.drop_column('address_id')

    # ### end Alembic commands ###
