"""empty message

Revision ID: f6212f495230
Revises: 0dad45b94c90
Create Date: 2024-04-13 01:46:05.315728

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6212f495230'
down_revision = '0dad45b94c90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('purchase_order_inventory_association_tbl',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('purchase_order_id', sa.Integer(), nullable=True),
    sa.Column('supplier_id', sa.Integer(), nullable=True),
    sa.Column('inventory_id', sa.Integer(), nullable=True),
    sa.Column('item_qty', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['inventory_id'], ['inventory_tbl.inventory_id'], ),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_order_tbl.purchase_order_id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['supplier_tbl.supplier_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('purchase_order_inventory_association')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('purchase_order_inventory_association',
    sa.Column('purchase_order_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('inventory_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('item_qty', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('supplier_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['inventory_id'], ['inventory_tbl.inventory_id'], name='purchase_order_inventory_association_inventory_id_fkey'),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_order_tbl.purchase_order_id'], name='purchase_order_inventory_association_purchase_order_id_fkey'),
    sa.ForeignKeyConstraint(['supplier_id'], ['supplier_tbl.supplier_id'], name='purchase_order_inventory_association_supplier_id_fkey')
    )
    op.drop_table('purchase_order_inventory_association_tbl')
    # ### end Alembic commands ###
